[package]
name = "ubsniff"
version = "0.1.4"
authors = ["Jay Kickliter <jay@kickliter.com>"]
edition = "2018"

[dependencies]
serialport = { version = "3", default-features = false }
structopt = "0.3"
ublox = { path = ".." }


[target.'cfg(target_os = "linux")'.dependencies]
i2c-linux = "0.1.2"
