[package]
name = "ublox"
version = "0.1.3"
authors = ["Jay Kickliter <jay@kickliter.com>"]
edition = "2018"

[workspace]
members = [ "ubsniff" ]
default-members = [ "ubsniff" ]

[dependencies]
nom = "4"

[dependencies.byteorder]
version = "1"
default-features = false
