[package]
name = "ublox"
version = "0.1.4"
authors = ["Jay Kickliter <jay@kickliter.com>"]
edition = "2018"

[workspace]
members = [ "ubsniff" ]
default-members = [ "ubsniff" ]

[dependencies]
bitfield = "0.13.2"
bytes = { version = "0.5.4", default-features = false }
log = "0.4.8"
